

#????
#????
spring:
  profiles:
    active: pro
---
#????

#????
server:
  port: 80
spring:
  profiles: pro
---
#????
server:
  port: 81
spring:
  profiles: dev
---
#????
server:
  port: 82
spring:
  config:
    activate:
      on-profile: test
