
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.167.33:12356/ssm_db
    username: root
    password: fengqiji2001
#  cache:
#    type: redis
#    redis:
##      use-key-prefix: true
##      cache-null-values: true
##      key-prefix: aa
#      time-to-live: 10s
  redis:
    host: localhost
    port: 6379

jetcache:
  remote:
    sms:
      type: redis
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50
      keyConvertor: fastjson

    default:
      type: redis
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50
      keyConvertor: fastjson
      valueEncode: java
      valueDecode: java
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson


#  cache:
#    type: simple
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
